[CmdletBinding()]
param(
    [ValidateSet('Smoke', 'Full')]
    [string]$Profile = 'Smoke',

    # Kept for compatibility with the pre-TC4 command line. Strict is now the default.
    [switch]$Strict,

    [switch]$Baseline,

    [switch]$ReuseWorld,

    [string]$WorldPreset = 'gravesown:after_the_silence'
)

. "$PSScriptRoot\common.ps1"

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

Enter-ProjectRoot
$javaHome = Use-ProjectJava
Write-Host "Using JAVA_HOME=$javaHome"

$runRoot = [System.IO.Path]::GetFullPath((Join-Path $script:ProjectRoot 'run-worldtest'))
$sentinel = Join-Path $runRoot '.gravesown-worldtest-root'
$worldName = 'world-audit'
$worldPath = [System.IO.Path]::GetFullPath((Join-Path $runRoot $worldName))
$reportDirectory = Join-Path $script:ProjectRoot 'build\reports\gravesown\world-audit'
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)

function Initialize-SafeWorldTestRoot {
    if (-not (Test-Path -LiteralPath $runRoot)) {
        New-Item -ItemType Directory -Path $runRoot | Out-Null
    }

    if (-not (Test-Path -LiteralPath $sentinel)) {
        $existing = @(Get-ChildItem -LiteralPath $runRoot -Force -ErrorAction Stop)
        if ($existing.Count -gt 0) {
            throw "Refusing to use $runRoot because its Gravesown test sentinel is missing and the directory is not empty."
        }
        [System.IO.File]::WriteAllText(
            $sentinel,
            "Owned by Gravesown worldtest.cmd. Never store personal worlds here.`r`n",
            $utf8NoBom
        )
    }
}

function Remove-SafeAuditWorld {
    $projectPrefix = [System.IO.Path]::GetFullPath($script:ProjectRoot).TrimEnd('\') + '\'
    if (-not $runRoot.StartsWith($projectPrefix, [System.StringComparison]::OrdinalIgnoreCase)) {
        throw "Refusing a world-test root outside the project workspace: $runRoot"
    }
    $rootPrefix = $runRoot.TrimEnd('\') + '\'
    if (-not $worldPath.StartsWith($rootPrefix, [System.StringComparison]::OrdinalIgnoreCase)) {
        throw "Refusing unsafe test-world path outside $runRoot`: $worldPath"
    }
    if ((Split-Path -Leaf $worldPath) -ne $worldName) {
        throw "Refusing unexpected test-world directory: $worldPath"
    }
    if (-not (Test-Path -LiteralPath $sentinel)) {
        throw "Refusing to remove a test world without sentinel: $sentinel"
    }
    if (Test-Path -LiteralPath $worldPath) {
        $runRootItem = Get-Item -LiteralPath $runRoot -Force
        $worldItem = Get-Item -LiteralPath $worldPath -Force
        if (($runRootItem.Attributes -band [System.IO.FileAttributes]::ReparsePoint) -ne 0 -or
            ($worldItem.Attributes -band [System.IO.FileAttributes]::ReparsePoint) -ne 0) {
            throw 'Refusing to recursively remove a world-test path containing a junction or symbolic link.'
        }
        Remove-Item -LiteralPath $worldPath -Recurse -Force
    }
}

function Write-AuditServerProperties {
    param([Parameter(Mandatory = $true)][long]$Seed)

    $escapedPreset = $WorldPreset.Replace(':', '\:')
    $properties = @(
        '# Generated by Gravesown worldtest.cmd. This directory is disposable.'
        'allow-flight=true'
        'allow-nether=false'
        'difficulty=normal'
        'enable-command-block=false'
        'enable-query=false'
        'enable-rcon=false'
        'enable-status=false'
        'enforce-secure-profile=false'
        'gamemode=creative'
        'generate-structures=true'
        'hardcore=false'
        "level-name=$worldName"
        "level-seed=$Seed"
        "level-type=$escapedPreset"
        'max-players=1'
        'max-tick-time=-1'
        'online-mode=false'
        'server-ip=127.0.0.1'
        'server-port=0'
        'simulation-distance=2'
        'spawn-animals=false'
        'spawn-monsters=false'
        'spawn-npcs=false'
        'spawn-protection=0'
        'sync-chunk-writes=true'
        'view-distance=2'
    )
    [System.IO.File]::WriteAllLines(
        (Join-Path $runRoot 'server.properties'),
        $properties,
        $utf8NoBom
    )
}

Initialize-SafeWorldTestRoot
if ($Strict -and $Baseline) {
    throw '-Strict and -Baseline cannot be used together.'
}
if ($ReuseWorld -and $Profile -eq 'Full') {
    throw '-ReuseWorld is only valid for the single-seed Smoke profile.'
}

if ($Profile -eq 'Full') {
    [long[]]$seeds = @(-7046029254386353131L, 8675309L, 2305843009213693951L)
    $radius = 8
}
else {
    [long[]]$seeds = @(-7046029254386353131L)
    $radius = 2
}

$strictEnforcement = -not $Baseline
$enforcement = if ($strictEnforcement) { 'strict' } else { 'baseline' }
$strictFailures = 0
$reports = @()

Write-Step "Running $Profile real-chunk world audit ($enforcement enforcement)"
foreach ($seed in $seeds) {
    if (-not $ReuseWorld) {
        Remove-SafeAuditWorld
    }
    elseif (-not (Test-Path -LiteralPath $worldPath)) {
        throw "Cannot reuse missing audit world: $worldPath"
    }

    Write-AuditServerProperties -Seed $seed
    $reportId = "{0}_seed_{1}" -f $Profile.ToLowerInvariant(), $seed
    $reportPath = Join-Path $reportDirectory "world-audit-$reportId.json"
    if (Test-Path -LiteralPath $reportPath) {
        Remove-Item -LiteralPath $reportPath -Force
    }

    $env:GRAVESOWN_WORLD_AUDIT_ENFORCEMENT = $enforcement
    $env:GRAVESOWN_WORLD_AUDIT_PROFILE = $Profile.ToLowerInvariant()
    $env:GRAVESOWN_WORLD_AUDIT_REPORT_ID = $reportId
    $env:GRAVESOWN_WORLD_AUDIT_RADIUS = [string]$radius
    $env:GRAVESOWN_WORLD_AUDIT_SAMPLE_LIMIT = '50'
    $env:GRAVESOWN_WORLD_AUDIT_REQUIRED_BIOME = 'gravesown:sown_grave'

    Write-Host "Generating and scanning seed $seed ($((2 * $radius + 1) * (2 * $radius + 1)) FULL chunks)..."
    Invoke-ProjectGradle 'runWorldTest'

    if (-not (Test-Path -LiteralPath $reportPath)) {
        throw "World audit server exited without writing $reportPath"
    }
    $report = Get-Content -LiteralPath $reportPath -Raw -Encoding UTF8 | ConvertFrom-Json
    if (-not $report.complete) {
        throw "World audit report is incomplete: $reportPath"
    }
    if ([long]$report.seed -ne $seed) {
        throw "World audit seed mismatch: requested $seed, report contains $($report.seed). Use a fresh world."
    }
    if ($report.status -eq 'ERROR') {
        throw "World audit scanner error: $($report.error). See $reportPath"
    }

    $reports += $reportPath
    Write-Host (
        "Seed {0}: status={1}, chunks={2}, positions={3}, violations={4}, duration={5}ms" -f
        $seed,
        $report.status,
        $report.totals.chunks,
        $report.totals.blockPositions,
        $report.violations.total,
        $report.durationMillis
    )

    if ($strictEnforcement -and $report.status -ne 'PASS') {
        $strictFailures++
    }
    elseif (-not $strictEnforcement -and $report.status -notin @('PASS', 'BASELINE_RECORDED')) {
        throw "Unexpected baseline audit status $($report.status): $reportPath"
    }
}

Write-Host ''
if ($strictFailures -gt 0) {
    Write-Host "WORLD CONTRACT FAIL: $strictFailures seed(s) contain forbidden world content." -ForegroundColor Red
    Write-Host "Reports: $reportDirectory" -ForegroundColor Yellow
    throw 'Strict Gravesown world audit failed.'
}

if ($strictEnforcement) {
    Write-Host 'WORLDTEST PASS: the strict Gravesown world contract is satisfied.' -ForegroundColor Green
}
else {
    Write-Host 'WORLDTEST HARNESS PASS: baseline reports were recorded successfully.' -ForegroundColor Green
    Write-Warning 'Baseline mode records forbidden content without failing. Use the default strict mode for acceptance.'
}
Write-Host "Reports: $reportDirectory" -ForegroundColor Green
